name: Continuous Deployment

on:
  push:
    branches:
      - main  # This workflow runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server_ip: [54.210.13.167, 54.162.59.154]  # Replace with your actual server IPs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up .pem key
        # Decode the PEM key from the GitHub secret and save it as a file
        run: |
          echo "${{ secrets.PEM_KEY_BASE64 }}" | base64 -d > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/capstone-project:latest  # Pull the Docker image

      - name: Deploy to Server
        run: |
          scp -i ~/deploy_key.pem -o StrictHostKeyChecking=no ./CAPSTONE-PROJECT-1/docker-compose.yml ec2-user@${{ matrix.server_ip }}:/home/ec2-user/  # Copy docker-compose to the server
          ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no ec2-user@${{ matrix.server_ip }} "docker-compose up -d"  # Run Docker Compose on the server

      - name: Clean up PEM file
        run: rm ~/deploy_key.pem
