name: Deploy Docker Image to HTTP Servers

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        nodes: ["10.0.2.168", "10.0.2.167"]  # IP addresses of HTTP servers for deployment

    steps:
      - name: Set up SSH key for connecting to the servers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}  # Using the private SSH key for the bastion server
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          # Configure SSH key for access with the correct name "hanankey.pem"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/hanankey.pem
          chmod 600 ~/.ssh/hanankey.pem

          # Connect to the server, pull the Docker image, and run the container
          ssh -i ~/.ssh/hanankey.pem -o StrictHostKeyChecking=no $SSH_USERNAME@${{ matrix.nodes }} << 'EOF'
            echo "Pulling Docker image from Docker Hub and running it on server ${{ matrix.nodes }}"
            docker pull hanangh/capstone-project:latest  # Pull the latest version of the Docker image
            docker stop myapp-container || true  # Stop any existing container with the same name, if it exists
            docker rm -f myapp-container || true  # Remove the existing container with the same name, if it exists
            docker run -d --name myapp-container -p 8081:80 hanangh/capstone-project:latest  # Run a new container on port 8081
          EOF
