name: Deploy to HTTP Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        server: 
            - {  ip: "10.0.2.126"}
            - {  ip: "10.0.2.127"}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker image
      run: docker pull hanangh/capstone-project:latest
    
    - name: Copy SSH key file
      env: 
        SSH_KEY: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
      run: | 
        echo "$SSH_KEY" > hananKey
        chmod 600 hananKey

    - name: Deploy Docker container
      run: |
        ssh -i hananKey root@${{ matrix.server.ip }} 'mkdir -p /capstone-project && cd /capstone-project && docker stop app || true && docker rm app || true && docker pull hanangh/capstone-project:latest && docker run -d --name app -p 8081:80 hanangh/capstone-project:latest'
