name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        # Example command to install dependencies
        sudo apt-get update
        sudo apt-get install -y curl git build-essential

    - name: Run Tests
      run: |
        # Example command to run tests
        # Replace this with actual commands to run your project’s tests
        echo "Running tests..."
        # Example: npm test, pytest, etc.
        exit 0

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Ensure the 'test' job completes successfully first

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/capstone-project:latest
